// ==================== 가중치 ====================
export const WEIGHTS = {
    emotion: 0.30,
    responsibility: 0.20,
    relationship: 0.20,
    values: 0.15,
    self: 0.15,
};

// ==================== 질문 데이터 ====================
// 연령·성별 → 시나리오(daily, school, work, romance) 로 구분
export const QUESTIONS = {
    // ---------- 10대 남성 ----------
    TEEN_MALE: {
        daily: {
            tm_1: {
                id: 'tm_1',
                category: 'emotion',
                text: { ko: '용돈이 생기면?' },
                options: {
                    1: '무조건 다 쓴다',
                    2: '사고 싶은 걸 산다',
                    3: '반은 쓰고 반은 모음',
                    4: '사고 싶은 걸 참음',
                    5: '미래를 위해 투자',
                },
            },
            tm_2: {
                id: 'tm_2',
                category: 'self',
                text: { ko: '자기 전 스마트폰으로?' },
                options: {
                    1: '숏폼 영상 시청',
                    2: '게임/카톡',
                    3: '웹서핑',
                    4: '내일 스케줄 확인',
                    5: '명상/일기 쓰기',
                },
            },
            tm_3: {
                id: 'tm_3',
                category: 'self',
                text: { ko: '방 청소 상태는?' },
                options: {
                    1: '발 디딜 틈 없음',
                    2: '정리하라고 혼나야 함',
                    3: '적당히 생활감 있음',
                    4: '직접 정리함',
                    5: '항상 각 잡혀 있음',
                },
            },
            tm_4: {
                id: 'tm_4',
                category: 'relationship',
                text: { ko: '주말에 부모님이 외식하자면?' },
                options: {
                    1: '메뉴가 내 위주여야 함',
                    2: '귀찮지만 따라감',
                    3: '부모님이 가자는 곳 감',
                    4: '부모님 기분 맞춰드림',
                    5: '내가 부모님 대접하고 싶음',
                },
            },
            tm_5: {
                id: 'tm_5',
                category: 'responsibility',
                text: { ko: '편의점에서 간식 고를 때?' },
                options: {
                    1: '무조건 신제품 도전',
                    2: '포장지 예쁜 것',
                    3: '맛있어 보이는 것',
                    4: '가성비 좋은 것',
                    5: '성분/칼로리 확인',
                },
            },
            tm_6: {
                id: 'tm_6',
                category: 'emotion',
                text: { ko: '가장 어른이 되었다고 느낄 때?' },
                options: {
                    1: '혼자 대중교통 탈 때',
                    2: '통장 잔고 볼 때',
                    3: '동생 챙길 때',
                    4: '부모님 힘든 거 보일 때',
                    5: '인생 고민할 때',
                },
            },
            tm_7: {
                id: 'tm_7',
                category: 'self',
                text: { ko: '스트레스 해소법은?' },
                options: {
                    1: '소리 지르기/게임',
                    2: '친구와 수다',
                    3: '잠자기',
                    4: '운동하기',
                    5: '혼자 조용히 생각하기',
                },
            },
            tm_8: {
                id: 'tm_8',
                category: 'relationship',
                text: { ko: 'SNS 게시물 올릴 때?' },
                options: {
                    1: '좋아요 수에 집착함',
                    2: '자주 올림',
                    3: '가끔 기록용',
                    4: '남들이 하는 만큼만',
                    5: '거의 안 함',
                },
            },
            tm_9: {
                id: 'tm_9',
                category: 'self',
                text: { ko: '새로운 취미를 시작하면?' },
                options: {
                    1: '장비부터 다 삼',
                    2: '금방 질림',
                    3: '꾸준히 해봄',
                    4: '깊게 파고듦',
                    5: '남에게 가르칠 정도',
                },
            },
            tm_10: {
                id: 'tm_10',
                category: 'values',
                text: { ko: '나에게 공부란?' },
                options: {
                    1: '하기 싫은 고역',
                    2: '엄마가 시켜서 함',
                    3: '남들 하니까 함',
                    4: '미래를 위한 수단',
                    5: '자아 성장의 과정',
                },
            },
        },
        school: {
            // 학교생활 질문 (same as daily for 10대 남성)
            tm_1: { /* same as above */ },
            tm_2: { /* same as above */ },
            tm_3: { /* same as above */ },
            tm_4: { /* same as above */ },
            tm_5: { /* same as above */ },
            tm_6: { /* same as above */ },
            tm_7: { /* same as above */ },
            tm_8: { /* same as above */ },
            tm_9: { /* same as above */ },
            tm_10: { /* same as above */ },
        },
        romance: {
            tm_11: {
                id: 'tm_11',
                category: 'relationship',
                text: { ko: '짝사랑 상대가 생기면?' },
                options: {
                    1: '친구에게 다 소문냄',
                    2: '장난치며 괴롭힘',
                    3: '주변을 맴돔',
                    4: '몰래 지켜보며 고심',
                    5: '진심 담아 고백',
                },
            },
            tm_12: {
                id: 'tm_12',
                category: 'relationship',
                text: { ko: '연애하면 가장 하고 싶은 것?' },
                options: {
                    1: '커플 템 맞추기',
                    2: '교복 데이트',
                    3: 'PC방/노래방 가기',
                    4: '도서관 데이트',
                    5: '미래 약속',
                },
            },
            tm_13: {
                id: 'tm_13',
                category: 'relationship',
                text: { ko: '고백받는다면 어디서?' },
                options: {
                    1: '사람 많은 공개 장소',
                    2: '둘만의 장소',
                    3: '카톡/문자',
                    4: '편지',
                    5: '자연스럽게 사귀게 됨',
                },
            },
            tm_14: {
                id: 'tm_14',
                category: 'relationship',
                text: { ko: '연인이 연락이 없다면?' },
                options: {
                    1: '화나서 폭풍 카톡',
                    2: '걱정돼서 계속 전화',
                    3: '기다리다 서운해함',
                    4: '바쁜가 보다 이해',
                    5: '자기 할 일 하며 기다림',
                },
            },
            tm_15: {
                id: 'tm_15',
                category: 'relationship',
                text: { ko: '기념일(100일) 챙기기?' },
                options: {
                    1: '성대한 이벤트',
                    2: '작은 선물',
                    3: '맛있는 것 먹기',
                    4: '서로 고마움 전달',
                    5: '넘어가도 상관없음',
                },
            },
            tm_16: {
                id: 'tm_16',
                category: 'relationship',
                text: { ko: '첫 키스에 대한 생각?' },
                options: {
                    1: '빨리 하고 싶음',
                    2: '호기심 가득',
                    3: '때가 되면 하겠지',
                    4: '소중하고 신중하게',
                    5: '사랑의 결실이라 믿음',
                },
            },
            tm_17: {
                id: 'tm_17',
                category: 'relationship',
                text: { ko: '데이트 비용 부담은?' },
                options: {
                    1: '돈 없으면 안 만남',
                    2: '내가 다 내고 싶음',
                    3: '더치페이',
                    4: '여유 있는 사람이 냄',
                    5: '부모님 도움 안 받고 해결',
                },
            },
            tm_18: {
                id: 'tm_18',
                category: 'relationship',
                text: { ko: '헤어지고 나서 사진은?' },
                options: {
                    1: '바로 삭제',
                    2: '보관함 이동',
                    3: '한참 뒤에 지움',
                    4: '그냥 둠',
                    5: '좋은 추억으로 간직',
                },
            },
            tm_19: {
                id: 'tm_19',
                category: 'relationship',
                text: { ko: '이상형 1순위 조건?' },
                options: {
                    1: '얼굴/키',
                    2: '성격/재미',
                    3: '나만 사랑해주는 사람',
                    4: '배울 점 있는 사람',
                    5: '가치관이 맞는 사람',
                },
            },
            tm_20: {
                id: 'tm_20',
                category: 'relationship',
                text: { ko: '부모님께 연애 사실을?' },
                options: {
                    1: '절대 비밀',
                    2: '걸릴 때까지 숨김',
                    3: '친한 친구처럼 공유',
                    4: '조언을 구함',
                    5: '당당하게 허락받음',
                },
            },
        },
        work: {}, // 10대는 직장 질문 없음
    },

    // ---------- 10대 여성 ----------
    TEEN_FEMALE: {
        daily: {
            tf_1: {
                id: 'tf_1',
                category: 'emotion',
                text: { ko: '수업 시간 나의 모습은?' },
                options: {
                    1: '대놓고 딴짓/잠',
                    2: '낙서하며 듣는 척',
                    3: '시키면 대답함',
                    4: '열심히 경청/필기',
                    5: '질문을 통해 깊게 탐구',
                },
            },
            tf_2: {
                id: 'tf_2',
                category: 'relationship',
                text: { ko: '선생님이 화내실 때?' },
                options: {
                    1: '속으로 욕함',
                    2: '왜 나만 갖구래',
                    3: '반성함',
                    4: '선생님 입장 이해',
                    5: '상황을 객관적으로 분석',
                },
            },
            tf_3: {
                id: 'tf_3',
                category: 'relationship',
                text: { ko: '짝꿍이 숙제 보여달라면?' },
                options: {
                    1: '흔쾌히 보여줌',
                    2: '사탕 하나 받고 보여줌',
                    3: '거절하고 직접 하라 함',
                    4: '설명하며 도와줌',
                    5: '선생님께 말씀드림',
                },
            },
            tf_4: {
                id: 'tf_4',
                category: 'responsibility',
                text: { ko: '급식 줄 설 때?' },
                options: {
                    1: '1등으로 뛰어감',
                    2: '친구랑 장난치며 대기',
                    3: '그냥 서 있음',
                    4: '뒷사람 배려함',
                    5: '조용히 질서 지킴',
                },
            },
            tf_5: {
                id: 'tf_5',
                category: 'relationship',
                text: { ko: '발표 수업을 할 때?' },
                options: {
                    1: '주목받아 즐거움',
                    2: '긴장되지만 해냄',
                    3: '평범하게 함',
                    4: '청중 반응 살피며 함',
                    5: '전문가처럼 전달함',
                },
            },
            tf_6: {
                id: 'tf_6',
                category: 'self',
                text: { ko: '쉬는 시간에 주로 하는 일?' },
                options: {
                    1: '복도 뛰어다님',
                    2: '친구와 수다',
                    3: '간식 먹기',
                    4: '책 보거나 다음 수업 준비',
                    5: '쪽잠/휴식',
                },
            },
            tf_7: {
                id: 'tf_7',
                category: 'emotion',
                text: { ko: '시험 성적이 낮게 나오면?' },
                options: {
                    1: '내일이면 잊음',
                    2: '속상해함',
                    3: '다음엔 잘하자 다짐',
                    4: '부족한 부분 복습',
                    5: '성적보다 배움에 집중',
                },
            },
            tf_8: {
                id: 'tf_8',
                category: 'emotion',
                text: { ko: '싫어하는 과목 시간은?' },
                options: {
                    1: '대놓고 잔다',
                    2: '멍 때린다',
                    3: '참고 듣는다',
                    4: '억지로라도 이해하려 함',
                    5: '모든 학문은 연결됨을 느낌',
                },
            },
            tf_9: {
                id: 'tf_9',
                category: 'self',
                text: { ko: '동아리를 고를 때?' },
                options: {
                    1: '제일 노는 곳',
                    2: '친구 따라감',
                    3: '관심 있는 분야',
                    4: '입시에 도움 되는 곳',
                    5: '내 적성 계발',
                },
            },
            tf_10: {
                id: 'tf_10',
                category: 'relationship',
                text: { ko: '학교 축제 참여도?' },
                options: {
                    1: '무대 주인공',
                    2: '열심히 참여/응원',
                    3: '적당히 구경',
                    4: '운영/스태프 조력',
                    5: '귀찮아서 쉬고 싶음',
                },
            },
        },
        school: {
            // same as daily for 10대 여성
            tf_1: { /* same as above */ },
            tf_2: { /* same as above */ },
            tf_3: { /* same as above */ },
            tf_4: { /* same as above */ },
            tf_5: { /* same as above */ },
            tf_6: { /* same as above */ },
            tf_7: { /* same as above */ },
            tf_8: { /* same as above */ },
            tf_9: { /* same as above */ },
            tf_10: { /* same as above */ },
        },
        romance: {
            // 10대 여성 연애 질문 (reuse same as TEEN_MALE romance for simplicity)
            tf_11: {
                id: 'tf_11',
                category: 'relationship',
                text: { ko: '짝사랑 상대가 생기면?' },
                options: {
                    1: '친구에게 다 소문냄',
                    2: '장난치며 괴롭힘',
                    3: '주변을 맴돔',
                    4: '몰래 지켜보며 고심',
                    5: '진심 담아 고백',
                },
            },
            // ... (other romance questions can be duplicated from TEEN_MALE romance) 
        },
        work: {},
    },

    // ---------- 20대 남성 ----------
    ADULT_MALE: {
        work: {
            twm_1: {
                id: 'twm_1',
                category: 'emotion',
                text: { ko: '직장에서 스트레스를 받을 때 어떻게 대처하나요?' },
                options: {
                    1: '소리 지르기/게임',
                    2: '친구와 수다',
                    3: '잠자기',
                    4: '운동하기',
                    5: '혼자 조용히 생각하기',
                },
            },
            twm_2: {
                id: 'twm_2',
                category: 'responsibility',
                text: { ko: '한 달 생활비를 어떻게 관리하나요?' },
                options: {
                    1: '무조건 다 쓰고',
                    2: '필요한 것만 사',
                    3: '절반은 모음',
                    4: '저축/투자',
                    5: '미래를 위해 계획',
                },
            },
            twm_3: {
                id: 'twm_3',
                category: 'relationship',
                text: { ko: '연인과 갈등이 생겼을 때 어떻게 해결하나요?' },
                options: {
                    1: '화내고 폭풍 카톡',
                    2: '대화로 풀기',
                    3: '시간 두고 생각',
                    4: '서로 이해하려 노력',
                    5: '관계 포기',
                },
            },
            twm_4: {
                id: 'twm_4',
                category: 'values',
                text: { ko: '직업을 선택할 때 가장 중요하게 생각하는 것은?' },
                options: {
                    1: '연봉',
                    2: '업무 만족도',
                    3: '성장 가능성',
                    4: '워크라이프 밸런스',
                    5: '사회적 의미',
                },
            },
            twm_5: {
                id: 'twm_5',
                category: 'emotion',
                text: { ko: '실패를 경험했을 때 감정은?' },
                options: {
                    1: '분노',
                    2: '좌절',
                    3: '반성',
                    4: '다음에 도전',
                    5: '무관심',
                },
            },
            twm_6: {
                id: 'twm_6',
                category: 'responsibility',
                text: { ko: '5년 뒤 목표가 있나요?' },
                options: {
                    1: '없음',
                    2: '대강 구상',
                    3: '구체적 계획',
                    4: '실행 중',
                    5: '달성 완료',
                },
            },
            twm_7: {
                id: 'twm_7',
                category: 'self',
                text: { ko: '자기계발에 투자하는 정도는?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 책 읽음',
                    3: '온라인 강의 수강',
                    4: '전문 교육 수료',
                    5: '전문가 수준',
                },
            },
            twm_8: {
                id: 'twm_8',
                category: 'relationship',
                text: { ko: '부모님과의 관계는?' },
                options: {
                    1: '거리가 멀다',
                    2: '가끔 연락',
                    3: '정기적 연락',
                    4: '함께 시간 보내기',
                    5: '가족 중심 생활',
                },
            },
            twm_9: {
                id: 'twm_9',
                category: 'values',
                text: { ko: '결혼에 대한 생각은?' },
                options: {
                    1: '당장',
                    2: '몇 년 뒤',
                    3: '조건 충족 시',
                    4: '비혼',
                    5: '미정',
                },
            },
            twm_10: {
                id: 'twm_10',
                category: 'self',
                text: { ko: '자신의 강점과 약점을 어떻게 파악하나요?' },
                options: {
                    1: '전혀 모른다',
                    2: '주변에 물어봄',
                    3: '자기 성찰',
                    4: '전문가 상담',
                    5: '명확히 인식',
                },
            },
        },
        romance: {
            // reuse twm_3 as romance specific
            twm_3: {
                id: 'twm_3',
                category: 'relationship',
                text: { ko: '연인과 갈등이 생겼을 때 어떻게 해결하나요?' },
                options: {
                    1: '화내고 폭풍 카톡',
                    2: '대화로 풀기',
                    3: '시간 두고 생각',
                    4: '서로 이해하려 노력',
                    5: '관계 포기',
                },
            },
        },
        daily: {},
        school: {},
    },

    // ---------- 20대 여성 ----------
    ADULT_FEMALE: {
        work: {
            twf_1: {
                id: 'twf_1',
                category: 'emotion',
                text: { ko: '직장에서 부당한 대우를 받았을 때 어떻게 하나요?' },
                options: {
                    1: '표정 관리 안 됨',
                    2: '속으로 욕하며 따름',
                    3: '정중하게 의견 제시',
                    4: '대안을 가지고 설득',
                    5: '사회 생활의 일부로 수용',
                },
            },
            twf_2: {
                id: 'twf_2',
                category: 'responsibility',
                text: { ko: '재테크나 저축을 하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔',
                    3: '정기적',
                    4: '전문가 상담',
                    5: '투자까지',
                },
            },
            twf_3: {
                id: 'twf_3',
                category: 'relationship',
                text: { ko: '연인과의 관계에서 가장 중요하게 생각하는 것은?' },
                options: {
                    1: '신뢰',
                    2: '소통',
                    3: '공동 목표',
                    4: '시간 공유',
                    5: '자유',
                },
            },
            twf_4: {
                id: 'twf_4',
                category: 'values',
                text: { ko: '커리어와 결혼·출산 중 어느 것을 우선시하나요?' },
                options: {
                    1: '커리어',
                    2: '결혼·출산',
                    3: '동시 진행',
                    4: 상황에 따라',
          5: '미정',
                },
            },
            twf_5: {
                id: 'twf_5',
                category: 'emotion',
                text: { ko: '외모·몸매에 대한 스트레스는?' },
                options: {
                    1: '심함',
                    2: '가끔',
                    3: '보통',
                    4: '신경 안 씀',
                    5: '긍정적',
                },
            },
            twf_6: {
                id: 'twf_6',
                category: 'responsibility',
                text: { ko: '건강 관리는 어떻게 하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 운동',
                    3: '정기적 운동',
                    4: '전문가 상담',
                    5: '건강식',
                },
            },
            twf_7: {
                id: 'twf_7',
                category: 'self',
                text: { ko: '자신만의 가치관은?' },
                options: {
                    1: '불명확',
                    2: '가끔 고민',
                    3: '명확히 있음',
                    4: '주변에 공유',
                    5: '삶의 지침',
                },
            },
            twf_8: {
                id: 'twf_8',
                category: 'relationship',
                text: { ko: '친구와의 관계는?' },
                options: {
                    1: '가깝다',
                    2: '보통',
                    3: '멀다',
                    4: '연락 자주',
                    5: '연락 거의 안 함',
                },
            },
            twf_9: {
                id: 'twf_9',
                category: 'emotion',
                text: { ko: '불안감을 느낄 때 어떻게 대처하나요?' },
                options: {
                    1: '혼자 끙끙',
                    2: '친구에게 털어놓음',
                    3: '운동',
                    4: '명상',
                    5: '전문가 상담',
                },
            },
            twf_10: {
                id: 'twf_10',
                category: 'self',
                text: { ko: '자기계발을 위해 무엇을 하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 책',
                    3: '온라인 강의',
                    4: '전문 교육',
                    5: '전문가 수준',
                },
            },
        },
        romance: {
            twf_3: {
                id: 'twf_3',
                category: 'relationship',
                text: { ko: '연인과의 관계에서 가장 중요하게 생각하는 것은?' },
                options: {
                    1: '신뢰',
                    2: '소통',
                    3: '공동 목표',
                    4: '시간 공유',
                    5: '자유',
                },
            },
        },
        daily: {},
        school: {},
    },

    // ---------- 30대 남성 ----------
    THIRTY_MALE: {
        work: {
            thm_1: {
                id: 'thm_1',
                category: 'emotion',
                text: { ko: '업무 스트레스를 어떻게 관리하나요?' },
                options: {
                    1: '소리 지르기/게임',
                    2: '친구와 수다',
                    3: '잠자기',
                    4: '운동하기',
                    5: '혼자 조용히 생각하기',
                },
            },
            thm_2: {
                id: 'thm_2',
                category: 'responsibility',
                text: { ko: '가계 재정을 어떻게 관리하나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 기록',
                    3: '앱 사용',
                    4: '전문가 상담',
                    5: '투자까지',
                },
            },
            thm_3: {
                id: 'thm_3',
                category: 'relationship',
                text: { ko: '배우자와 갈등이 생겼을 때 어떻게 해결하나요?' },
                options: {
                    1: '화내고 폭풍 카톡',
                    2: '대화로 풀기',
                    3: '시간 두고 생각',
                    4: '서로 이해하려 노력',
                    5: '관계 포기',
                },
            },
            thm_4: {
                id: 'thm_4',
                category: 'values',
                text: { ko: '일과 가정 중 무엇을 우선시하나요?' },
                options: {
                    1: '일',
                    2: '가정',
                    3: '균형',
                    4: '상황에 따라',
                    5: '미정',
                },
            },
            thm_5: {
                id: 'thm_5',
                category: 'emotion',
                text: { ko: '중년 위기를 어떻게 느끼나요?' },
                options: {
                    1: '전혀 안 느낌',
                    2: '가끔',
                    3: '보통',
                    4: '많이 느낌',
                    5: '극심함',
                },
            },
            thm_6: {
                id: 'thm_6',
                category: 'responsibility',
                text: { ko: '5년 뒤 목표가 있나요?' },
                options: {
                    1: '없음',
                    2: '대강 구상',
                    3: '구체적 계획',
                    4: '실행 중',
                    5: '달성 완료',
                },
            },
            thm_7: {
                id: 'thm_7',
                category: 'self',
                text: { ko: '건강 관리는 어떻게 하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 운동',
                    3: '정기적 운동',
                    4: '전문가 상담',
                    5: '건강식',
                },
            },
            thm_8: {
                id: 'thm_8',
                category: 'relationship',
                text: { ko: '부모님과의 관계는?' },
                options: {
                    1: '거리가 멀다',
                    2: '가끔 연락',
                    3: '정기적 연락',
                    4: '함께 시간 보내기',
                    5: '가족 중심 생활',
                },
            },
            thm_9: {
                id: 'thm_9',
                category: 'values',
                text: { ko: '결혼에 대한 생각은?' },
                options: {
                    1: '당장',
                    2: '몇 년 뒤',
                    3: '조건 충족 시',
                    4: '비혼',
                    5: '미정',
                },
            },
            thm_10: {
                id: 'thm_10',
                category: 'self',
                text: { ko: '자신의 강점과 약점을 어떻게 파악하나요?' },
                options: {
                    1: '전혀 모른다',
                    2: '주변에 물어봄',
                    3: '자기 성찰',
                    4: '전문가 상담',
                    5: '명확히 인식',
                },
            },
        },
        romance: {
            thm_3: {
                id: 'thm_3',
                category: 'relationship',
                text: { ko: '배우자와 갈등이 생겼을 때 어떻게 해결하나요?' },
                options: {
                    1: '화내고 폭풍 카톡',
                    2: '대화로 풀기',
                    3: '시간 두고 생각',
                    4: '서로 이해하려 노력',
                    5: '관계 포기',
                },
            },
        },
        daily: {},
        school: {},
    },

    // ---------- 30대 여성 ----------
    THIRTY_FEMALE: {
        work: {
            thf_1: {
                id: 'thf_1',
                category: 'emotion',
                text: { ko: '육아와 일을 병행하면서 느끼는 스트레스는?' },
                options: {
                    1: '소리 지르기/게임',
                    2: '친구와 수다',
                    3: '잠자기',
                    4: '운동하기',
                    5: '혼자 조용히 생각하기',
                },
            },
            thf_2: {
                id: 'thf_2',
                category: 'responsibility',
                text: { ko: '가계 재정 관리에 얼마나 참여하나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 기록',
                    3: '앱 사용',
                    4: '전문가 상담',
                    5: '투자까지',
                },
            },
            thf_3: {
                id: 'thf_3',
                category: 'relationship',
                text: { ko: '배우자와의 관계를 어떻게 유지하나요?' },
                options: {
                    1: '자주 대화',
                    2: '함께 활동',
                    3: '서로 공간 존중',
                    4: '전문가 상담',
                    5: '관계 포기',
                },
            },
            thf_4: {
                id: 'thf_4',
                category: 'values',
                text: { ko: '자녀 교육에서 가장 중요하게 생각하는 것은?' },
                options: {
                    1: '학업 성취',
                    2: '인성 교육',
                    3: '진로 탐색',
                    4: '사회성',
                    5: '자율성',
                },
            },
            thf_5: {
                id: 'thf_5',
                category: 'emotion',
                text: { ko: '커리어를 포기한 것에 대해 어떻게 생각하나요?' },
                options: {
                    1: '후회',
                    2: '수용',
                    3: '새로운 목표 찾음',
                    4: '가족 중심',
                    5: '무관심',
                },
            },
            thf_6: {
                id: 'thf_6',
                category: 'responsibility',
                text: { ko: '건강 관리는 어떻게 하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 운동',
                    3: '정기적 운동',
                    4: '전문가 상담',
                    5: '건강식',
                },
            },
            thf_7: {
                id: 'thf_7',
                category: 'self',
                text: { ko: '자신만의 시간을 얼마나 확보하나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔',
                    3: '주 1~2시간',
                    4: '주 3~4시간',
                    5: '매일 충분히',
                },
            },
            thf_8: {
                id: 'thf_8',
                category: 'relationship',
                text: { ko: '친구 관계를 어떻게 유지하나요?' },
                options: {
                    1: '자주 만나',
                    2: '연락 자주',
                    3: '가끔 만나',
                    4: '소셜 미디어',
                    5: '거의 안 함',
                },
            },
            thf_9: {
                id: 'thf_9',
                category: 'emotion',
                text: { ko: '엄마로서의 죄책감을 어떻게 다루나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 느낀다',
                    3: '자주 고민',
                    4: '전문가 상담',
                    5: '수용',
                },
            },
            thf_10: {
                id: 'thf_10',
                category: 'self',
                text: { ko: '자기계발을 계속하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 책',
                    3: '온라인 강의',
                    4: '전문 교육',
                    5: '전문가 수준',
                },
            },
        },
        romance: {
            thf_3: {
                id: 'thf_3',
                category: 'relationship',
                text: { ko: '배우자와의 관계를 어떻게 유지하나요?' },
                options: {
                    1: '자주 대화',
                    2: '함께 활동',
                    3: '서로 공간 존중',
                    4: '전문가 상담',
                    5: '관계 포기',
                },
            },
        },
        daily: {},
        school: {},
    },

    // ---------- 40대 남성 ----------
    FORTY_MALE: {
        work: {
            fm_1: {
                id: 'fm_1',
                category: 'emotion',
                text: { ko: '중년의 위기를 어떻게 극복하고 있나요?' },
                options: {
                    1: '전혀 안 느낌',
                    2: '가끔',
                    3: '보통',
                    4: '많이 느낌',
                    5: '극심함',
                },
            },
            fm_2: {
                id: 'fm_2',
                category: 'responsibility',
                text: { ko: '노후 준비는 얼마나 하고 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 저축',
                    3: '정기적 투자',
                    4: '전문가 상담',
                    5: '충분히 준비',
                },
            },
            fm_3: {
                id: 'fm_3',
                category: 'relationship',
                text: { ko: '자녀와의 관계는?' },
                options: {
                    1: '거리가 멀다',
                    2: '가끔 연락',
                    3: '정기적 연락',
                    4: '함께 시간',
                    5: '가족 중심',
                },
            },
            fm_4: {
                id: 'fm_4',
                category: 'values',
                text: { ko: '인생에서 가장 중요한 가치는?' },
                options: {
                    1: '돈',
                    2: '명예',
                    3: '가족',
                    4: '건강',
                    5: '평화',
                },
            },
            fm_5: {
                id: 'fm_5',
                category: 'emotion',
                text: { ko: '건강 문제에 대한 불안은?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔',
                    3: '보통',
                    4: '많이',
                    5: '극심',
                },
            },
            fm_6: {
                id: 'fm_6',
                category: 'responsibility',
                text: { ko: '부모님 부양에 대해 어떻게 생각하나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 도움',
                    3: '정기적 지원',
                    4: '전문가 상담',
                    5: '전적으로 책임',
                },
            },
            fm_7: {
                id: 'fm_7',
                category: 'self',
                text: { ko: '새로운 것을 배우는 것에 대해 어떻게 생각하나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔',
                    3: '주기적',
                    4: '전문가 과정',
                    5: '전문가 수준',
                },
            },
            fm_8: {
                id: 'fm_8',
                category: 'relationship',
                text: { ko: '배우자와의 관계는?' },
                options: {
                    1: '거리가 멀다',
                    2: '가끔 연락',
                    3: '정기적 연락',
                    4: '함께 시간',
                    5: '가족 중심',
                },
            },
            fm_9: {
                id: 'fm_9',
                category: 'values',
                text: { ko: '은퇴에 대한 계획이 있나요?' },
                options: {
                    1: '전혀 안 함',
                    2: '가끔 생각',
                    3: '계획 중',
                    4: '구체적 준비',
                    5: '완료',
                },
            },
            fm_10: {
                id: 'fm_10',
                category: 'self',
                text: { ko: '인생을 돌아볼 때 어떤 생각이 드나요?' },
                options: {
                    1: '후회',
                    2: '보람',
                    3: '평온',
                    4: '성취감',
                    5: '무감각',
                },
            },
        },
        romance: {},
        daily: {},
        school: {},
    },

    // ---------- 40대 여성 ----------
    FORTY_FEMALE: {
        work: {
            // Placeholder 10 questions (ff_1~ff_10) – similar structure
            ff_1: { id: 'ff_1', category: 'emotion', text: { ko: '아침에 눈뜨면?' }, options: { 1: '더 자고 싶다', 2: '오늘도 파이팅', 3: '일어나기 힘들다', 4: '건강 생각하며 스트레칭', 5: '명상으로 하루 시작' } },
            ff_2: { id: 'ff_2', category: 'responsibility', text: { ko: '자녀 교육에 대해?' }, options: { 1: '최고의 학원 지원', 2: '하고 싶은 거 시킴', 3: '기본만 함', 4: '건강하게만 자라라', 5: '자녀의 인성 교육 집중' } },
            ff_3: { id: 'ff_3', category: 'self', text: { ko: '노화 방지를 위해?' }, options: { 1: '시술/성형', 2: '비싼 화장품', 3: '규칙적 운동', 4: '충분한 휴식/영양', 5: '내면의 평온 유지' } },
            ff_4: { id: 'ff_4', category: 'relationship', text: { ko: '동창회 모임 성격?' }, options: { 1: '누가 잘나갔나 확인', 2: '옛 친구와 수다', 3: '인맥 확보', 4: '의무적 참석', 5: '안 나감' } },
            ff_5: { id: 'ff_5', category: 'self', text: { ko: '나만의 스트레스 해소?' }, options: { 1: '음주/가무', 2: '쇼핑', 3: '운동', 4: '조용한 여행', 5: '독서/글쓰기' } },
            ff_6: { id: 'ff_6', category: 'self', text: { ko: '전자기기 사용 능력?' }, options: { 1: '젊은이만큼 잘함', 2: '필요한 건 배움', 3: '자식에게 물어봄', 4: '쓰던 것만 씀', 5: '기계가 싫음' } },
            ff_7: { id: 'ff_7', category: 'values', text: { ko: '정치/사회 뉴스?' }, options: { 1: '적극적 참여/토론', 2: '관심 있게 시청', 3: '내 생각 확고', 4: '답답해서 안 봄', 5: '객관적 관망' } },
            ff_8: { id: 'ff_8', category: 'responsibility', text: { ko: '가계부 쓰시나요?' }, options: { 1: '안 씀', 2: '머릿속으로 계산', 3: '앱으로 대충 기록', 4: '꼼꼼히 기록', 5: '자산 전문가에게 상담' } },
            ff_9: { id: 'ff_9', category: 'relationship', text: { ko: '부모님에 대한 마음?' }, options: { 1: '죄송함 가득', 2: '효도하려 노력', 3: '자주 찾아뵐', 4: '건강이 제일 걱정', 5: '내 미래 모습 같음' } },
            ff_10: { id: 'ff_10', category: 'values', text: { ko: '노후 준비 상태?' }, options: { 1: '이제 생각 중', 2: '저축 위주', 3: '연금/부동산 확보', 4: '준비 완료', 5: '삶을 정리하는 중' } },
        },
        romance: {},
        daily: {},
        school: {},
    },

    // ---------- 50대 남성 ----------
    FIFTY_MALE: {
        work: {
            fm50_1: { id: 'fm50_1', category: 'emotion', text: { ko: '건강 관리 1순위?' }, options: { 1: '등산/골프', 2: '걷기', 3: '영양제', 4: '정기검진', 5: '마음 다스리기' } },
            fm50_2: { id: 'fm50_2', category: 'relationship', text: { ko: '자녀의 독립에 대해?' }, options: { 1: '시원섭섭함', 2: '서운함', 3: '축하해줌', 4: '드디어 자유', 5: '걱정만 앞섬' } },
            fm50_3: { id: 'fm50_3', category: 'emotion', text: { ko: '갱년기 극복법?' }, options: { 1: '운동', 2: '가족과 대화', 3: '병원 치료', 4: '혼자만의 시간', 5: '취미 몰입' } },
            fm50_4: { id: 'fm50_4', category: 'values', text: { ko: '퇴직 후 로망?' }, options: { 1: '세계 일주', 2: '전원주택', 3: '작은 사업', 4: '자원봉사', 5: '손주 보기' } },
            fm50_5: { id: 'fm50_5', category: 'self', text: { ko: '스마트폰 활용?' }, options: { 1: '앱 개발/공부', 2: '뱅킹/쇼핑', 3: '유튜브 시청', 4: '전화/문자', 5: '기계가 무서움' } },
            fm50_6: { id: 'fm50_6', category: 'relationship', text: { ko: '나에게 친구란?' }, options: { 1: '죽고 못 사는 사이', 2: '취미 같이 하는 사이', 3: '가끔 보는 사이', 4: '연락만 하는 사이', 5: '필요 없음' } },
            fm50_7: { id: 'fm50_7', category: 'values', text: { ko: '인생에서 가장 중요한 것?' }, options: { 1: '돈', 2: '명예', 3: '가족', 4: '건강', 5: '평화' } },
            fm50_8: { id: 'fm50_8', category: 'self', text: { ko: '새로운 배움(악기 등)?' }, options: { 1: '적극 참여', 2: '생각만 함', 3: '남들 하니까', 4: '어려워서 포기', 5: '관심 없음' } },
            fm50_9: { id: 'fm50_9', category: 'self', text: { ko: '거울 속 내 모습?' }, options: { 1: '아직 청춘', 2: '세월이 느껴짐', 3: '안쓰러움', 4: '받아들임', 5: '보기 싫음' } },
            fm50_10: { id: 'fm50_10', category: 'values', text: { ko: '노후 자금 준비?' }, options: { 1: '풍족함', 2: '적당함', 3: '부족함', 4: '막막함', 5: '자식에게 기대야 함' } },
        },
        romance: {},
        daily: {},
        school: {},
    },

    // ---------- 50대 여성 ----------
    FIFTY_FEMALE: {
        work: {
            ff50_1: { id: 'ff50_1', category: 'emotion', text: { ko: '건강 관리 1순위?' }, options: { 1: '등산/골프', 2: '걷기', 3: '영양제', 4: '정기검진', 5: '마음 다스리기' } },
            ff50_2: { id: 'ff50_2', category: 'relationship', text: { ko: '자녀의 독립에 대해?' }, options: { 1: '시원섭섭함', 2: '서운함', 3: '축하해줌', 4: '드디어 자유', 5: '걱정만 앞섬' } },
            ff50_3: { id: 'ff50_3', category: 'emotion', text: { ko: '갱년기 극복법?' }, options: { 1: '운동', 2: '가족과 대화', 3: '병원 치료', 4: '혼자만의 시간', 5: '취미 몰입' } },
            ff50_4: { id: 'ff50_4', category: 'values', text: { ko: '퇴직 후 로망?' }, options: { 1: '세계 일주', 2: '전원주택', 3: '작은 사업', 4: '자원봉사', 5: '손주 보기' } },
            ff50_5: { id: 'ff50_5', category: 'self', text: { ko: '스마트폰 활용?' }, options: { 1: '앱 개발/공부', 2: '뱅킹/쇼핑', 3: '유튜브 시청', 4: '전화/문자', 5: '기계가 무서움' } },
            ff50_6: { id: 'ff50_6', category: 'relationship', text: { ko: '나에게 친구란?' }, options: { 1: '죽고 못 사는 사이', 2: '취미 같이 하는 사이', 3: '가끔 보는 사이', 4: '연락만 하는 사이', 5: '필요 없음' } },
            ff50_7: { id: 'ff50_7', category: 'values', text: { ko: '인생에서 가장 중요한 것?' }, options: { 1: '돈', 2: '명예', 3: '가족', 4: '건강', 5: '평화' } },
            ff50_8: { id: 'ff50_8', category: 'self', text: { ko: '새로운 배움(악기 등)?' }, options: { 1: '적극 참여', 2: '생각만 함', 3: '남들 하니까', 4: '어려워서 포기', 5: '관심 없음' } },
            ff50_9: { id: 'ff50_9', category: 'self', text: { ko: '거울 속 내 모습?' }, options: { 1: '아직 청춘', 2: '세월이 느껴짐', 3: '안쓰러움', 4: '받아들임', 5: '보기 싫음' } },
            ff50_10: { id: 'ff50_10', category: 'values', text: { ko: '노후 자금 준비?' }, options: { 1: '풍족함', 2: '적당함', 3: '부족함', 4: '막막함', 5: '자식에게 기대야 함' } },
        },
        romance: {},
        daily: {},
        school: {},
    },

    // ---------- 60대 이상 (시니어) ----------
    SENIOR: {
        daily: {
            sen_1: { id: 'sen_1', category: 'self', text: { ko: '하루 중 가장 즐거운 시간?' }, options: { 1: '모임/외출', 2: '운동', 3: 'TV/유튜브', 4: '손주 보기', 5: '명상/기도' } },
            sen_2: { id: 'sen_2', category: 'self', text: { ko: '건강 유지 비법?' }, options: { 1: '등산/걷기', 2: '소식', 3: '영양제', 4: '병원 정기 방문', 5: '마음 비우기' } },
            sen_3: { id: 'sen_3', category: 'values', text: { ko: '제사/명절에 대한 생각?' }, options: { 1: '꼭 지켜야 함', 2: '간소화해야 함', 3: '안 하고 싶음', 4: '자식들 뜻대로', 5: '여행 가고 싶음' } },
            sen_4: { id: 'sen_4', category: 'self', text: { ko: '요즘 유행하는 문화?' }, options: { 1: '배우고 싶음', 2: '신기함', 3: '어색함', 4: '한심해 보임', 5: '관심 없음' } },
            sen_5: { id: 'sen_5', category: 'self', text: { ko: '옷차림의 기준?' }, options: { 1: '젊고 세련되게', 2: '깔끔하게', 3: '편하게', 4: '남의 시선 의식', 5: '아무거나' } },
            sen_6: { id: 'sen_6', category: 'self', text: { ko: '가장 그리운 시절?' }, options: { 1: '어린 시절', 2: '청춘 시절', 3: '아이들 키울 때', 4: '직장 다닐 때', 5: '지금이 제일 좋음' } },
            sen_7: { id: 'sen_7', category: 'self', text: { ko: '죽음에 대한 준비?' }, options: { 1: '자서전/정리', 2: '유언/상속', 3: '마음의 준비', 4: '두려움', 5: '생각 안 함' } },
            sen_8: { id: 'sen_8', category: 'self', text: { ko: '나에게 돈이란?' }, options: { 1: '즐길 수단', 2: '병원비/노후', 3: '자식 줄 것', 4: '없으면 비참한 것', 5: '부질없는 것' } },
            sen_9: { id: 'sen_9', category: 'self', text: { ko: '거주 환경 선호?' }, options: { 1: '도시 아파트', 2: '전원주택', 3: '실버타운', 4: '자식 집 근처', 5: '고향 집' } },
            sen_10: { id: 'sen_10', category: 'self', text: { ko: '삶의 보람?' }, options: { 1: '자식 성공', 2: '내 건강', 3: '사회 봉사', 4: '배움의 즐거움', 5: '무탈한 하루' } },
        },
        // 사회생활, 부부/가족생활 등 추가 시 별도 시나리오로 확장 가능
    },
};

export default QUESTIONS;
